### ISSUE TITLE
Translations repository

### ISSUE THREAD

**Issue by dudemelo** [Behat/Gherkin#103]
The current [URL to i18n.json](https://github.com/Behat/Gherkin/blob/master/bin/update_i18n#L4) is broken because the gherkin2 repository has been moved. Will we use the new gherkin2 repository or keep using the gherkin3?

**Comment by stof** [comment]
We should update our script to read translations from https://github.com/cucumber/gherkin/blob/master/gherkin-languages.json instead of the gherkin2 repo. All gherkin 2 translations have been synchronized into gherkin 3, but gherkin 2 is now unmaintained and so translations won't be updated anymore.
Note that the gherkin 3 repo uses a different format for their language file, so it is not just a matter of updating the URL.

I will do this update for the next release of the library (as I will need to run the script anyway).
